src/java/com/lms/ReturnBookController.java
package com.lms;

import com.lms.util.JsfUtil;
import com.lms.util.JsfUtil.PersistAction;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@ManagedBean(name = "returnBookController")
@SessionScoped
public class ReturnBookController implements Serializable {

    @EJB
    private com.lms.ReturnBookFacade ejbFacade;
    private List<ReturnBook> items = null;
    private ReturnBook selected;

    public ReturnBookController() {
    }

    public ReturnBook getSelected() {
        return selected;
    }

    public void setSelected(ReturnBook selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private ReturnBookFacade getFacade() {
        return ejbFacade;
    }

    public ReturnBook prepareCreate() {
        selected = new ReturnBook();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("ReturnBookCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("ReturnBookUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("ReturnBookDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<ReturnBook> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public List<ReturnBook> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<ReturnBook> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = ReturnBook.class)
    public static class ReturnBookControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ReturnBookController controller = (ReturnBookController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "returnBookController");
            return controller.getFacade().find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof ReturnBook) {
                ReturnBook o = (ReturnBook) object;
                return getStringKey(o.getReturnBookId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), ReturnBook.class.getName()});
                return null;
            }
        }

    }

}

web/returnBook/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ReturnBookCreateDlg" widgetVar="ReturnBookCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateReturnBookTitle}">
            <h:form id="ReturnBookCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{returnBookController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateReturnBookLabel_returnBookId}" for="returnBookId" />
                        <p:inputText id="returnBookId" value="#{returnBookController.selected.returnBookId}" title="#{bundle.CreateReturnBookTitle_returnBookId}" required="true" requiredMessage="#{bundle.CreateReturnBookRequiredMessage_returnBookId}"/>
                        <p:outputLabel value="#{bundle.CreateReturnBookLabel_returnDate}" for="returnDate" />
                        <p:calendar id="returnDate" pattern="MM/dd/yyyy" value="#{returnBookController.selected.returnDate}" title="#{bundle.EditReturnBookTitle_returnDate}" required="true" requiredMessage="#{bundle.EditReturnBookRequiredMessage_returnDate}" showOn="button"/>
                        <p:outputLabel value="#{bundle.CreateReturnBookLabel_userId}" for="userId" />
                        <p:selectOneMenu id="userId" value="#{returnBookController.selected.userId}" >
                            <f:selectItems value="#{userController.itemsAvailableSelectOne}"
                                           var="userIdItem"
                                           itemValue="#{userIdItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateReturnBookLabel_bookId}" for="bookId" />
                        <p:selectOneMenu id="bookId" value="#{returnBookController.selected.bookId}" required="true" requiredMessage="#{bundle.EditReturnBookRequiredMessage_bookId}">
                            <f:selectItems value="#{bookController.itemsAvailableSelectOne}"
                                           var="bookIdItem"
                                           itemValue="#{bookIdItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{returnBookController.create}" value="#{bundle.Save}" update="display,:ReturnBookListForm:datalist,:growl" oncomplete="handleSubmit(args,'ReturnBookCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ReturnBookCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/returnBook/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ReturnBookEditDlg" widgetVar="ReturnBookEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditReturnBookTitle}">
            <h:form id="ReturnBookEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{returnBookController.selected != null}">
                        <p:outputLabel value="#{bundle.EditReturnBookLabel_returnBookId}" for="returnBookId" />
                        <p:inputText id="returnBookId" value="#{returnBookController.selected.returnBookId}" title="#{bundle.EditReturnBookTitle_returnBookId}" required="true" requiredMessage="#{bundle.EditReturnBookRequiredMessage_returnBookId}"/>
                        <p:outputLabel value="#{bundle.EditReturnBookLabel_returnDate}" for="returnDate" />
                        <p:calendar id="returnDate" pattern="MM/dd/yyyy" value="#{returnBookController.selected.returnDate}" title="#{bundle.EditReturnBookTitle_returnDate}" required="true" requiredMessage="#{bundle.EditReturnBookRequiredMessage_returnDate}" showOn="button"/>
                        <p:outputLabel value="#{bundle.EditReturnBookLabel_userId}" for="userId" />
                        <p:selectOneMenu id="userId" value="#{returnBookController.selected.userId}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{userController.itemsAvailableSelectOne}"
                                           var="userIdItem"
                                           itemValue="#{userIdItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditReturnBookLabel_bookId}" for="bookId" />
                        <p:selectOneMenu id="bookId" value="#{returnBookController.selected.bookId}" required="true" requiredMessage="#{bundle.EditReturnBookRequiredMessage_bookId}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{bookController.itemsAvailableSelectOne}"
                                           var="bookIdItem"
                                           itemValue="#{bookIdItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{returnBookController.update}" value="#{bundle.Save}" update="display,:ReturnBookListForm:datalist,:growl" oncomplete="handleSubmit(args, 'ReturnBookEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ReturnBookEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/returnBook/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListReturnBookTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="ReturnBookListForm">
                <p:panel header="#{bundle.ListReturnBookTitle}">
                    <p:dataTable id="datalist" value="#{returnBookController.items}" var="item"
                                 selectionMode="single" selection="#{returnBookController.selected}"
                                 paginator="true"
                                 rowKey="#{item.returnBookId}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListReturnBookTitle_returnBookId}"/>
                            </f:facet>
                            <h:outputText value="#{item.returnBookId}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListReturnBookTitle_returnDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.returnDate}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListReturnBookTitle_userId}"/>
                            </f:facet>
                            <h:outputText value="#{item.userId}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListReturnBookTitle_bookId}"/>
                            </f:facet>
                            <h:outputText value="#{item.bookId}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{returnBookController.prepareCreate}" update=":ReturnBookCreateForm" oncomplete="PF('ReturnBookCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":ReturnBookViewForm" oncomplete="PF('ReturnBookViewDialog').show()" disabled="#{empty returnBookController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":ReturnBookEditForm" oncomplete="PF('ReturnBookEditDialog').show()" disabled="#{empty returnBookController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{returnBookController.destroy}" update=":growl,datalist" disabled="#{empty returnBookController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/returnBook/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ReturnBookViewDlg" widgetVar="ReturnBookViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewReturnBookTitle}">
            <h:form id="ReturnBookViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{returnBookController.selected != null}">
                        <h:outputText value="#{bundle.ViewReturnBookLabel_returnBookId}"/>
                        <h:outputText value="#{returnBookController.selected.returnBookId}" title="#{bundle.ViewReturnBookTitle_returnBookId}"/>
                        <h:outputText value="#{bundle.ViewReturnBookLabel_returnDate}"/>
                        <h:outputText value="#{returnBookController.selected.returnDate}" title="#{bundle.ViewReturnBookTitle_returnDate}">
                            <f:convertDateTime pattern="MM/dd/yyyy" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewReturnBookLabel_userId}"/>
                        <h:outputText value="#{returnBookController.selected.userId}" title="#{bundle.ViewReturnBookTitle_userId}"/>
                        <h:outputText value="#{bundle.ViewReturnBookLabel_bookId}"/>
                        <h:outputText value="#{returnBookController.selected.bookId}" title="#{bundle.ViewReturnBookTitle_bookId}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="ReturnBookViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>