src/java/com/lms/FeedbackController.java
package com.lms;

import com.lms.util.JsfUtil;
import com.lms.util.JsfUtil.PersistAction;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@ManagedBean(name = "feedbackController")
@SessionScoped
public class FeedbackController implements Serializable {

    @EJB
    private com.lms.FeedbackFacade ejbFacade;
    private List<Feedback> items = null;
    private List<Feedback> filteredItems;
    private Feedback selected;

    public List<Feedback> getFilteredItems() {
        return filteredItems;
    }

    public void setFilteredItems(List<Feedback> filteredItems) {
        this.filteredItems = filteredItems;
    }

    public FeedbackController() {
    }

    public Feedback getSelected() {
        return selected;
    }

    public void setSelected(Feedback selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private FeedbackFacade getFacade() {
        return ejbFacade;
    }

    public Feedback prepareCreate() {
        selected = new Feedback();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("FeedbackCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("FeedbackUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("FeedbackDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Feedback> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public List<Feedback> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Feedback> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Feedback.class)
    public static class FeedbackControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            FeedbackController controller = (FeedbackController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "feedbackController");
            return controller.getFacade().find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Feedback) {
                Feedback o = (Feedback) object;
                return getStringKey(o.getFeedbackId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Feedback.class.getName()});
                return null;
            }
        }

    }

}

src/java/com/lms/SessionBean.java
package com.lms;
 
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
 
public class SessionBean {
 
    public static HttpSession getSession() {
        return (HttpSession) FacesContext.getCurrentInstance()
                .getExternalContext().getSession(false);
    }
 
    public static HttpServletRequest getRequest() {
        return (HttpServletRequest) FacesContext.getCurrentInstance()
                .getExternalContext().getRequest();
    }
 
    public static String getUserName() {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance()
                .getExternalContext().getSession(false);
        return session.getAttribute("username").toString();
    }
 
    public static String getUserId() {
        HttpSession session = getSession();
        if (session != null)
            return (String) session.getAttribute("userid");
        else
            return null;
    }
}

web/booksAvailable.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListBookTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="BookListForm">
                <p:panel header="#{bundle.ListBookTitle}">
                    <p:dataTable id="datalist" value="#{bookController.items}" var="item"
                                 selectionMode="single" selection="#{bookController.selected}"
                                 paginator="true"
                                 rowKey="#{item.bookId}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 filteredValue="#{bookController.filteredItems}"
                                 widgetVar="book"
                                 >
                        
                        <f:facet name="header">
                            <p:outputPanel>
                                <h:outputText value="Search all fields:" />
                                <p:inputText id="globalFilter" onkeyup="PF('book').filter()" style="width:150px" placeholder="Enter keyword"/>
                            </p:outputPanel>
                        </f:facet>


                        <p:column filterBy="#{item.bookId}" headerText="Id" footerText="contains" filterMatchMode="contains">
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_bookId}"/>
                            </f:facet>
                            <h:outputText value="#{item.bookId}"/>
                        </p:column>
                        <p:column filterBy="#{item.bookName}" headerText="Id" footerText="contains" filterMatchMode="contains">
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_bookName}"/>
                            </f:facet>
                            <h:outputText value="#{item.bookName}"/>
                        </p:column>
                        <p:column filterBy="#{item.bookEdition}" headerText="Id" footerText="contains" filterMatchMode="contains">
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_bookEdition}"/>
                            </f:facet>
                            <h:outputText value="#{item.bookEdition}"/>
                        </p:column>
                        <p:column filterBy="#{item.bookNumber}" headerText="Id" footerText="contains" filterMatchMode="contains">
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_bookNumber}"/>
                            </f:facet>
                            <h:outputText value="#{item.bookNumber}"/>
                        </p:column>
                        <p:column filterBy="#{item.publisher}" headerText="Id" footerText="contains" filterMatchMode="contains">
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_publisher}"/>
                            </f:facet>
                            <h:outputText value="#{item.publisher}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_quantity}"/>
                            </f:facet>
                            <h:outputText value="#{item.quantity}"/>
                        </p:column>
                        <p:column filterBy="#{item.bookStatus}" headerText="Id" footerText="contains" filterMatchMode="contains">
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_bookStatus}"/>
                            </f:facet>
                            <h:outputText value="#{item.bookStatus}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_borrowedBookCount}"/>
                            </f:facet>
                            <h:outputText value="#{item.borrowedBookCount}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.Available}"/>
                            </f:facet>
                            <h:outputText value="#{item.quantity-item.reserveBookCount}"/>
                        </p:column>
                        <p:column filterBy="#{item.barcodeId}" headerText="Id" filterMatchMode="contains">
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_barcodeId}"/>
                            </f:facet>
                            <h:outputText value="#{item.barcodeId}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Option"/>
                            </f:facet>
                            <p:commandButton disabled="#{bookController.disable(item)}" value="#{bundle.reserve}" action="#{bookController.reserve(item)}" />
                        </p:column>
                    </p:dataTable>
                    <h:commandLink>
                        <p:graphicImage library="images" name="xml.png"/>
                        <p:dataExporter type="xml" target="datalist" fileName="booksList" pageOnly="true" />
                    </h:commandLink>

                    <h:commandLink>
                        <p:graphicImage library="images" name="csv.png" />
                        <p:dataExporter type="csv" target="datalist" fileName="booksList" pageOnly="true" />
                    </h:commandLink>

                    <h:commandLink>
                        <p:graphicImage library="images" name="pdf.png" />
                        <p:dataExporter type="pdf" target="datalist" fileName="booksList" pageOnly="true" />
                    </h:commandLink>

                    <h:commandLink>
                        <p:graphicImage library="images" name="excel.png" />
                        <p:dataExporter type="xls" target="datalist" fileName="booksList" pageOnly="true"/>
                    </h:commandLink>                    
                </p:panel>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/booksBorrowed.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListBorrowBookTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="BorrowBookListForm">
                <p:panel header="#{bundle.ListBorrowBookTitle}">
                    <p:dataTable id="datalist" value="#{borrowBookController.items}" var="item"
                                 selectionMode="single" selection="#{borrowBookController.selected}"
                                 paginator="true"
                                 rowKey="#{item.borrowBookId}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBorrowBookTitle_borrowBookId}"/>
                            </f:facet>
                            <h:outputText value="#{item.borrowBookId}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBorrowBookTitle_borrowDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.borrowDate}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBorrowBookTitle_expiryDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.expiryDate}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBorrowBookTitle_userId}"/>
                            </f:facet>
                            <h:outputText value="#{item.userId}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBorrowBookTitle_bookId}"/>
                            </f:facet>
                            <h:outputText value="#{item.bookId}"/>
                        </p:column>
                    </p:dataTable>
                    <h:commandLink>
                        <p:graphicImage library="images" name="xml.png"/>
                        <p:dataExporter type="xml" target="datalist" fileName="borrowedBooksList" pageOnly="true" />
                    </h:commandLink>

                    <h:commandLink>
                        <p:graphicImage library="images" name="csv.png" />
                        <p:dataExporter type="csv" target="datalist" fileName="borrowedBooksList" pageOnly="true" />
                    </h:commandLink>

                    <h:commandLink>
                        <p:graphicImage library="images" name="pdf.png" />
                        <p:dataExporter type="pdf" target="datalist" fileName="borrowedBooksList" pageOnly="true" />
                    </h:commandLink>

                    <h:commandLink>
                        <p:graphicImage library="images" name="excel.png" />
                        <p:dataExporter type="xls" target="datalist" fileName="borrowedBooksList" pageOnly="true"/>
                    </h:commandLink>                    
                </p:panel>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/booksReserved.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListReserveBookTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="ReserveBookListForm">
                <p:panel header="#{bundle.ListReserveBookTitle}">
                    <p:dataTable id="datalist" value="#{reserveBookController.items}" var="item"
                                 selectionMode="single" selection="#{reserveBookController.selected}"
                                 paginator="true"
                                 rowKey="#{item.reserveBookId}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 filteredValue="#{reserveBookController.filteredItems}"
                                 widgetVar="book"
                                 >
                        
                        <f:facet name="header">
                            <p:outputPanel>
                                <h:outputText value="Search all fields:" />
                                <p:inputText id="globalFilter" onkeyup="PF('book').filter()" style="width:150px" placeholder="Enter keyword"/>
                            </p:outputPanel>
                        </f:facet>

                        <p:column filterBy="#{item.reserveBookId}" headerText="Id" footerText="contains" filterMatchMode="contains">
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListReserveBookTitle_reserveBookId}"/>
                            </f:facet>
                            <h:outputText value="#{item.reserveBookId}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListReserveBookTitle_reserveStartDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.reserveStartDate}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListReserveBookTitle_reserveFinishDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.reserveFinishDate}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </p:column>
                        <p:column filterBy="#{item.userId}" headerText="Id" footerText="contains" filterMatchMode="contains">
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListReserveBookTitle_userId}"/>
                            </f:facet>
                            <h:outputText value="#{item.userId}"/>
                        </p:column>
                        <p:column filterBy="#{item.bookId}" headerText="Id" footerText="contains" filterMatchMode="contains">
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListReserveBookTitle_bookId}"/>
                            </f:facet>
                            <h:outputText value="#{item.bookId}"/>
                        </p:column>
                    </p:dataTable>
                    <h:commandLink>
                        <p:graphicImage library="images" name="xml.png"/>
                        <p:dataExporter type="xml" target="datalist" fileName="booksReserved" pageOnly="true" />
                    </h:commandLink>

                    <h:commandLink>
                        <p:graphicImage library="images" name="csv.png" />
                        <p:dataExporter type="csv" target="datalist" fileName="booksReserved" pageOnly="true" />
                    </h:commandLink>

                    <h:commandLink>
                        <p:graphicImage library="images" name="pdf.png" />
                        <p:dataExporter type="pdf" target="datalist" fileName="booksReserved" pageOnly="true" />
                    </h:commandLink>

                    <h:commandLink>
                        <p:graphicImage library="images" name="excel.png" />
                        <p:dataExporter type="xls" target="datalist" fileName="booksReserved" pageOnly="true"/>
                    </h:commandLink>                    
                </p:panel>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/contactUs.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ContactUs}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form>
                <h:panelGrid columns="1" cellspacing="30" styleClass="margin">
                    <h:panelGrid columns="1" cellspacing="2" styleClass="contact_text">
                        <h:outputText value="Kathford International College of Engineering " style="font-weight: bold"/>
                        <h:outputText value="and Management (Engineering and Admin Block)" style="font-weight: bold"/>
                        <h:outputText value="Ring Road, Balkumari Chowk, Lalitpur" />
                        <h:outputText value="Phone: 01-5201241, 5201911" />
                        <h:outputText value="email: info@kathford.edu.np" />
                    </h:panelGrid>
                    <h:panelGrid columns="1" cellspacing="2" styleClass="contact_text">
                        <h:outputText value="Kathford International College of Engineering " style="font-weight: bold "/>
                        <h:outputText value="and Management (BBA and B.Sc. CSIT Block)" style="font-weight: bold"/>
                        <h:outputText value="Ring Road, Way to Chyasal from Balkumari Chowk, " />
                        <h:outputText value="Lalitpur" />
                        <h:outputText value="Phone: 01-5006446, 5006112" />
                        <h:outputText value="email: info@kathford.edu.np" />
                    </h:panelGrid>

                </h:panelGrid>




            </h:form>
        </ui:define>
    </ui:composition>










</html>

web/dashboard.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Home</title>
        <h:outputStylesheet name="css/jsfcrud.css"/>
    </h:head>
    <ui:composition template="/template.xhtml">
        <ui:define name="body">
            <p:chart type="metergauge" model="#{chartBean.meterGaugeModel1}" style="width:650px;height:490px; float: left " />

            <p:chart type="pie" model="#{chartBean.pieModel2}" style="width:650px;height:490px; float: right" />
        </ui:define>
    </ui:composition>




</html>

web/home.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Home</title>
        <h:outputStylesheet name="css/jsfcrud.css"/>
    </h:head>
    <ui:composition template="/template.xhtml">
        <ui:define name="body">

            <h:form id="user_form" prependId="false">
                <p:panel>
                    <p:panelGrid columns="4">
                        <p:selectOneMenu id="country" value="#{userController.choose}" style="width:150px">
                            <f:selectItem itemLabel="Barcode" itemValue="barcode" noSelectionOption="true" />
                            <f:selectItem itemLabel="Username" itemValue="username" noSelectionOption="true" />
                            <p:ajax update="dtable" event="change"/>
                            <p:ajax update="rdtable" event="change"/>
                        </p:selectOneMenu>
                        <p:inputText id="name" value="#{userController.selected.username}" required="true"  requiredMessage="Username required" placeholder="Enter your username"/>
                        <p:commandButton id="id1" value="Search" actionListener="#{userController.searchUser()}" icon="ui-icon-check" update="dtable"/>


                    </p:panelGrid>
                </p:panel>

                <h1><h:outputText value="User Profile"/></h1>
                <p:dataTable id="dtable" value="#{userController.u}" var="user">
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="UserId"/>
                        </f:facet>
                        <h:outputText binding="#{userid}" value="#{user.userId}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Username"/>
                        </f:facet>
                        <h:outputText value="#{user.username}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Contact"/>
                        </f:facet>
                        <h:outputText value="#{user.contact}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Email"/>
                        </f:facet>
                        <h:outputText value="#{user.email}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Address"/>
                        </f:facet>
                        <h:outputText value="#{user.address}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Image"/>
                        </f:facet>
                        <h:outputText value="#{user.image}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Name"/>
                        </f:facet>
                        <h:outputText value="#{user.name}"/>
                    </p:column>
                </p:dataTable>




                <h1><h:outputText value="Reserved Books"/></h1>
                <p:dataTable id="rdtable" value="#{userController.r}" var="item">
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="ReserveBookId"/>
                        </f:facet>
                        <h:outputText value="#{item.reserveBookId}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="ReserveStartDate"/>
                        </f:facet>
                        <h:outputText value="#{item.reserveStartDate}">
                            <f:convertDateTime pattern="MM/dd/yyyy" />
                        </h:outputText>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="ReserveFinishDate"/>
                        </f:facet>
                        <h:outputText value="#{item.reserveFinishDate}">
                            <f:convertDateTime pattern="MM/dd/yyyy" />
                        </h:outputText>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="UserId"/>
                        </f:facet>
                        <h:outputText value="#{item.userId}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="BookId"/>
                        </f:facet>
                        <h:outputText value="#{item.bookId}"/>
                    </p:column>
                </p:dataTable>
            </h:form>
        </ui:define>
    </ui:composition>

</html>